CREATE TABLE topico (
    id BIGINT NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(100) NOT NULL,
    mensaje TEXT NOT NULL,
    fechaDeCreacion DATE NOT NULL,
    status ENUM('ABIERTO', 'CERRADO', 'RESUELTO') NOT NULL DEFAULT 'ABIERTO',
    autor VARCHAR(100) NOT NULL,
    curso VARCHAR(100) NOT NULL,

    PRIMARY KEY (id)
);